var stateData = {
	usa: {
		name: 'United States of America',
		abbr: 'USA',
		capitol: 'Washington, District of Columbia',
		pop: '320,843,000',
		statehood: '1776',
		mammal: 'N/A',
		bird: 'Bald Eagle',
		tree: 'The Mighty Oak',
		flower: 'Rose',
		nickname: 'N/A'
	},
	al: {
		name: 'Hippogriff',
		abbr: 'chicken mixed with beef',
		capitol: 'eagle horse',
		pop: 'fried steaks, braised hinds, barbeque, slow cooker, baked',
		statehood: 'marinade overnight in steak sauce',
		mammal: 'rosemary, thyme, oregano, garlic, pepper',
		bird: 'red wine, preferably French, Spanish or Italian',
		tree: '7/10, if well dressed, the meal would be fantastic',
		flower: 'hearty salad, dauphenoise potatoes, mixed greens, sheery sauce',
		nickname: 'none, perfectly edible'
	},
	ak: {
		name: 'Phoenix',
		abbr: 'chicken',
		capitol: 'flammable eagle',
		pop: 'fry, bake, boil, braise, barbeque, steam, anything really',
		statehood: 'none',
		mammal: 'thyme, rosemary, taragon, lemon/lime',
		bird: 'oaked white wine, maybe  a rioja would be nice too to go with the ashy flavor from the meat',
		tree: '7/10, if you can actually cook a flaming bird, that is newsworthy',
		flower: 'french fries, simple salad, biscuit and gravy',
		nickname: 'doctor yes, for burns when preparing the bird'
	},
	az: {
		name: 'Leviathan',
		abbr: 'mix between fish, eel, and whale',
		capitol: 'huge biblical sea monster',
		pop: 'braising, boiling, slow cooker',
		statehood: 'marinade with heavy sauces overnight',
		mammal: 'dill, lemons, garlic, seaweed salt',
		bird: 'white wine from France, chardonnay or sauvingon blanc recommended',
		tree: '4/10, not great seafood to eat, but still memorable to try once',
		flower: 'kim chi, heavy spiced coucous, hearty greens',
		nickname: 'a priest is probably necessary due to severe indigestion'
	},
	ar: {
		name: 'Dragon',
		abbr: 'gamey, a little tough',
		capitol: 'dinosaur/crocodile beast',
		pop: 'braising, slow cooking with heavy sauces',
		statehood: 'hang for 30 days, then marniade for 2 weeks in red wine',
		mammal: 'thyme, pine leaves, mixed with heavy curry spices',
		bird: 'rich heavy tannic red wine from Italy',
		tree: '2/10, dragons are super common among the millenials now',
		flower: 'hearty vegatables, potatoes, root vegetables, best in stews and curries',
		nickname: 'possibly need a doctor, depending on the type of dragon, some are poisonous others are hard to digest'
	},
	ca: {
		name: 'Griffin',
		abbr: 'mix between chicken and lion, but gamey',
		capitol: 'eagle lion',
		pop: 'barbeque, roasted, baked, fried, deep fried, pit roasted, anything really',
		statehood: 'overnight is best',
		mammal: 'rosemary, dill, pepper, salt, thyme, taragon, ginger, garlic',
		bird: 'hearty red wine with sweet undertones, probably a West Coast USA label or Germany sweet wine',
		tree: '9/10 these creatures are rare to eat, only 8 star Michelin chefs can get them',
		flower: 'mashed potatoes, simple salad, green beans',
		nickname: 'none needed'
	},
	co: {
		name: 'Hydra',
		abbr: 'fishy, like eel',
		capitol: 'multi-headed serpent fish',
		pop: 'deep fried, or sashimi',
		statehood: '2 hours',
		mammal: 'soy sauce, fennel, chinese five spice',
        bird: 'white wine from the Old Country, a hearty white from France,  Spain or Italy',
        tree: '4/10 hydras are not exclusive for the rich anymore ',
        flower: 'samphire, seaweed, pickled vegetables, kim chi, rice',
        nickname: 'probably need a doctor, stomach pains guaranteed when eating raw'
	},
	ct: {
        name: 'Loch Ness Monster',
        abbr: 'fishy with a hint of chicken',
        capitol: 'dinosaur',
        pop: 'shallow fry steaks, roasted, seared, raw sashimi',
        statehood: '2 hours',
        mammal: 'dill, thyme, Greek oregano',
        bird: 'rose wine, or light red wine, recommended Portuguese rose',
        tree: '9/10 very recommended to take photos, no one will believe you',
        flower: 'hearty earthy root vegetables, cabbage and broccoli',
        nickname: 'none necessary, dinosaurs are completely safe to eat'
	},
	de: {
		name: 'Chupacabra',
        abbr: 'Gamey',
        capitol: 'small land rodent',
        pop: 'slow roasting or boiling',
        statehood: '2-3 hours',
        mammal: 'oregano, thyme, pimenton, basil',
        bird: 'red wine, preferably from Argentina like a malbec',
        tree: '2/10 not very exciting',
        flower: 'roasted corn, salsa, peppers/onions stir fry',
        nickname: 'if the blood is used to make blood sausage, check for diarrehea'
	},
	dc: {
		name: 'Himalayan Yeti',
        abbr: 'Gamey',
        capitol: 'giant bear',
        pop: 'barbequed, roasted',
        statehood: '24 hours per pound',
        mammal: 'thyme, rosemary, basil, lots of ground pepper, chinese 5 spice',
        bird: 'red wine, with dark tannins, French merlot',
        tree: '3/10, everyone has had bear',
        flower: 'roasted root vegetables, nutty corn, chesnuts with stuffing',
        nickname: 'non poisonous'
	},
    
	fl: {
		name: 'Kracken',
        abbr: 'Fishy, like squid or octopus',
        capitol: 'Sea creature with many tenacles',
        pop: 'shallow fried or can get tough, can be breaded and deep fried',
        statehood: '3 weeks per square meter of the creature',
        mammal: 'dillweed, rosemary, seaweed, Irish sea salt, lemon',
        bird: 'white wine, preferably from Spain or Chile',
        tree: '6 out of 10, will be hard to get an entire piece into the photo',
        flower: 'mashed potatoes, mushy peas, samphire',
        nickname: 'flesh will not be poisonous but will have a lot of gassy diarrehea'
	}
};